[package]
name = "fast-io-cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1.6.0"
memmap2 = "0.7.1"
linereader = "0.4.0"
simdutf8 = "0.1.4"